sonar.projectKey=outfit
sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.exclusions=**/generated/**,**/build/**
sonar.java.binaries=build/classes/java/main
sonar.java.test.binaries=build/classes/java/test
