### Create size
POST {{host}}/catalog/sizes
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "description": "P"
}

###

### List sizes
GET {{host}}/catalog/sizes?page=0&size=20
Authorization: Bearer {{token}}
Content-Type: application/json

###

### Search sizes by prefix (typeahead)
GET {{host}}/catalog/sizes?q=Med&page=0&size=10
Authorization: Bearer {{token}}
Content-Type: application/json

###

### Get size by ID
GET {{host}}/catalog/sizes/1
Authorization: Bearer {{token}}
Content-Type: application/json

###

### Rename size
PUT {{host}}/catalog/sizes/1
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "description": "Pequeno"
}

###

### Delete size
DELETE {{host}}/catalog/sizes/1
Authorization: Bearer {{token}}
Content-Type: application/json
