### Get all cities
GET {{host}}/shared/cities
Authorization: Bearer {{token}}
Content-Type: application/json

###

### Get city by IBGE code
GET {{host}}/shared/cities/3550308
Authorization: Bearer {{token}}
Content-Type: application/json